@baseUrl = http://localhost:3000
### Read all films with File variable
GET {{baseUrl}}/films

###
GET {{baseUrl}}/films/3

### Create a drink
POST {{baseUrl}}/films
Content-Type: application/json

{
  "title": "The Matrix",
  "director": "Lana Wachowski, Lilly Wachowski",
  "duration": -1,
  "description": "https://www.imdb.com/title/tt0133093/",
  "imageUrl": "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg"
}